### ISSUE TITLE
Error running example/main.py

### ISSUE THREAD

**Issue by guilhermebr** [avelino/nacho#3]
When running example/main.py returns the exception:

```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from nacho.multithreading import Superviser
  File "/Users/guilhermebr/Development/nacho/nacho/example/nacho/multithreading.py", line 39, in <module>
    class ChildProcess:
  File "/Users/guilhermebr/Development/nacho/nacho/example/nacho/multithreading.py", line 71, in ChildProcess
    @tulip.task
AttributeError: 'module' object has no attribute 'task'
```

$ pip freeze
Jinja2==2.7.1
MarkupSafe==0.18
blinker==1.3
quik==0.2.1
-e hg+https://code.google.com/p/tulip/@2c359b3120082b55ec2d4d9891ede17224f26fa3#egg=tulip-dev

**Comment by guilhermebr** [comment]
It's not a bug.
This happen because have one old version of tulip installed in my virtualenv (env/src/tulip).
